# Generated by Django 4.1 on 2022-11-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='id_pelicula',
            new_name='id',
        ),
    ]
