# Generated by Django 4.1 on 2022-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_pelicula_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='top10',
            field=models.BooleanField(default=False, null=True, verbose_name='Top'),
        ),
    ]
