# Generated by Django 4.1 on 2023-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_pelicula_top10'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagenlocal',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='ImagenLocal'),
        ),
    ]
