# Generated by Django 4.1 on 2023-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_actor_pelicula_genero_pelicula_subgenero1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='textoactor',
            field=models.TextField(blank=True, default='', null=True, verbose_name='TextoActor'),
        ),
    ]
