# Generated by Django 4.1 on 2023-02-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_actor_textoactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombredirector', models.CharField(max_length=100)),
                ('imagendirector', models.ImageField(null=True, upload_to='libreria/static/img', verbose_name='ImagenDirector')),
                ('textodirector', models.TextField(blank=True, default='', null=True, verbose_name='TextoDirector')),
            ],
        ),
    ]
