# Generated by Django 4.1 on 2023-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagenlocal',
            field=models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='ImagenLocal'),
        ),
    ]
