# Generated by Django 4.1 on 2023-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_pelicula_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
