# Generated by Django 4.1 on 2023-06-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_actor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
