# Generated by Django 4.1 on 2023-10-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_director_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='vista',
            field=models.BooleanField(default=False, null=True, verbose_name='Vista'),
        ),
    ]
