# Generated by Django 4.1 on 2024-07-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_pelicula_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cajitavertical',
            field=models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='CajitaVertical'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Imagen1'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Imagen2'),
        ),
    ]
